bug fix try No. 1
Build 3.8 to Build 3.10 throw the following error:

FAILED tests/test_grippers.py::TestGrippers::test_grippers - AssertionError: False is not true

Solution:

robot was changed to test_robot